version : "3.8"

services:
  devcontainer_game_card_exo:
    build:
      context: .
      dockerfile : Dockerfile
      args :
        - PORT=${DEVPORT}
        - DEVMODE=true 
        - USER_NAME=${USER_NAME}
        - USER_ID=${USER_ID}
        - GROUP_NAME=${GROUP_NAME}
        - GROUP_ID=${GROUP_ID}
    command: ["sleep", "infinity"]
    volumes:
      - .:/workspace:rw
    ports:
      - "${DEVPORT}:${DEVPORT}"