version : "3.8"

networks:
  card_game_network:
    driver : bridge

volumes:
  db_game_card_data:

services:
  devcontainer_game_card_exo:
    build:
      context: .
      dockerfile : Dockerfile
      args :
        - PORT=${DEVPORT}
        - DEVMODE=true 
        - USER_NAME=${USER_NAME}
        - USER_ID=${USER_ID}
        - GROUP_NAME=${GROUP_NAME}
        - GROUP_ID=${GROUP_ID}
    command: ["sleep", "infinity"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME : ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD : ${POSTGRES_PASSWORD}
    restart: always  
    networks:
        - card_game_network
    volumes:
      - .:/workspace:rw
    ports:
      - "${DEVPORT}:${DEVPORT}"
    depends_on:
      - db_game_card  
  db_game_card:
    image: postgres:16.10-alpine
    container_name: postgres_db_game_card
    restart: always
    volumes:
      - db_game_card_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - card_game_network  
    ports:
      - "5432:5432"    