version : "3.8"

services:
  devcontainer_game_card_exo:
    build:
      context: .devcontainer
      dockerfile : Dockerfile
      args :
        - USER_NAME=${USER_NAME}
        - USER_ID=${USER_ID}
        - GROUP_NAME=${GROUP_NAME}
        - GROUP_ID=${GROUP_ID}
        - DEVMODE=${DEVMODE}
    command: ["sleep", "infinity"]
    volumes:
      - .:/workspace:rw
    ports:
      - "${DEVPORT}:${DEVPORT}"